alias pmmk='python manage.py makemigrations'
alias pmm='python manage.py migrate'
alias pmr='python manage.py runserver'
alias pmc='python manage.py collectstatic'
alias pmcu='python manage.py createsuperuser'
alias pmms='python manage.py makemessages'
alias pmcm='python manage.py compilemessages'